spring.application.name=infosPatients

#database configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${URL_BDD}
spring.datasource.username=${USERNAME_BDD}
spring.datasource.password=${PASSWORD_BDD}

################### Hibernate Configuration ##########################

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server.port=${SERVER_PORT:8080}

# swagger-ui
springdoc.swagger-ui.path=/doc
springdoc.api-docs.path=/patient/v3/api-docs
api.server.gateway.url=${API_SERVER_GATEWAY_URL}