spring.application.name=infosPatients

#database configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/medilabo
spring.datasource.username=admin
spring.datasource.password=password

################### Hibernate Configuration ##########################

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=9000